name: tt_diary
description: A new Flutter application.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

module:androidX:
  true


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^5.0.0

  google_sign_in: ^5.0.0
  intl: ^0.17.0
  font_awesome_flutter: ^8.12.0
  qr_flutter: ^4.0.0
  quiver: ^3.0.0
  http: ^0.13.0


   # add dependency for Google Analytics for Firebase
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^8.0.2
  firebase_core: ^1.4.0  # add dependency for Firebase Core
  firebase_crashlytics: ^2.1.1

  flutter_launcher_icons: any
  pedantic_mono: ^1.13.0+3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"






dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icon/


# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
  fonts:
    - family: TrainOne
      fonts:
        - asset: assets/fonts/TrainOne-Regular.ttf
    - family: kiwiMaru
      fonts:
        - asset: assets/fonts/KiwiMaru-Regular.ttf


# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages


